"""Add duration_days to WarmupStrategy

Revision ID: 3288dd937cba
Revises: 3affb814f526
Create Date: 2025-05-23 01:07:30.601295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3288dd937cba'
down_revision: Union[str, None] = '3affb814f526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warmup_strategies', sa.Column('duration_days', sa.Integer(), nullable=False, server_default="7"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warmup_strategies', 'duration_days')
    # ### end Alembic commands ###
