"""Add subscription_plan_id to WarmupStrategy

Revision ID: 372700ef3a63
Revises: d5ad4999016e
Create Date: 2025-05-23 00:30:42.347326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372700ef3a63'
down_revision: Union[str, None] = 'd5ad4999016e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
