"""Change active_days to ARRAY(String)

Revision ID: 7c4f8bd7087a
Revises: b4aa46387b61
Create Date: 2025-05-23 01:40:05.511263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4f8bd7087a'
down_revision: Union[str, None] = 'b4aa46387b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
