"""Add FK: subscription_plan_id to WarmupStrategy

Revision ID: 8378cb7692e6
Revises: 372700ef3a63
Create Date: 2025-05-23 00:32:25.834163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8378cb7692e6'
down_revision: Union[str, None] = '372700ef3a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warmup_strategies', sa.Column('subscription_plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warmup_strategies', 'subscription_plans', ['subscription_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warmup_strategies', type_='foreignkey')
    op.drop_column('warmup_strategies', 'subscription_plan_id')
    # ### end Alembic commands ###
