"""Add prompt relationship to EmailLog

Revision ID: 8682ecdecac3
Revises: fe3cf5b95048
Create Date: 2025-05-23 03:40:08.896153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8682ecdecac3'
down_revision: Union[str, None] = 'fe3cf5b95048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('email_logs', sa.Column('prompt_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_email_logs_prompt_id', 'email_logs', 'ai_prompts', ['prompt_id'], ['id'])
    op.add_column('email_logs', sa.Column('target_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_email_logs_target_id', 'email_logs', 'warmup_targets', ['target_id'], ['id'])

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
