"""Fix active_days column type to ARRAY

Revision ID: b4aa46387b61
Revises: 3f401dc5b34b
Create Date: 2025-05-23 01:38:35.374123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4aa46387b61'
down_revision: Union[str, None] = '3f401dc5b34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
