"""Fix warmup strategy subscription plan relation

Revision ID: d5ad4999016e
Revises: 32c3ab6f0619
Create Date: 2025-05-23 00:29:34.697985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ad4999016e'
down_revision: Union[str, None] = '32c3ab6f0619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
